# environment
seed: 42
episodes: 200

# replay buffer
batch_size: 256
buffer_size: 1.0e+6
initial_samples: 2000

# network
hidden_size: 256

# criterion
criterion_name: Criterion
gamma: 0.99
alpha: 0.2

# update
tau: 5.0e-3
lr: 3.0e-4
